Repository metacraft-labs/codetracer, pull requests merged in 2025-05, with the labels that each got.

#116 fix: fix e2e test traceId parsing
  ui-tests/tests/lib/ct_helpers.ts
Labels: bug, cla-signed, test, ct entrypoint

#117 prepare release: 25.05.1
  CHANGELOG.md
  README.md
  src/ct/version.nim
Labels: cla-signed

#109 prepare github action to work with codetracer ci
  .github/actions/setup-nix/action.yml
  .github/workflows/codetracer.yml
Labels: cla-signed, build, CI

#127 fix `ct run` for now for wasm/rust (but not other wasm langs)
  src/ct/db_backend_record.nim
  src/ct/trace/record.nim
  src/ct/trace/run.nim
  src/ct/utilities/language_detection.nim
Labels: bug, cla-signed, ct-entrypoint, wasm

#125 Add dependabot config for github action workflows
  .github/dependabot.yml
Labels: enhancement, cla-signed, ci

#131 Fix interactive replay not quitting cleanly when getting a terminal interrupt
  src/ct/cli/interactive_replay.nim
Labels: bug, cla-signed, cli, ct-entrypoint

#137 chore(wazero): Bump wazero version
  flake.lock
Labels: cla-signed, build, packaging, nix

#161 Add tests for small-lang
  src/small-lang/Cargo.lock
  src/small-lang/Cargo.toml
  src/small-lang/src/main.rs
  src/small-lang/tests/basic.rs
Labels: cla-signed, codex

#154 feat(examples): add `noir_simple_sha` to example programs
  examples/noir_simple_sha/Nargo.toml
  examples/noir_simple_sha/Prover.toml
  examples/noir_simple_sha/src/main.nr
Labels: cla-signed
