Repository metacraft-labs/codetracer, pull requests merged in 2025-03, with the labels that each got.

#55 fix: small fixes, cleanups and improvements for `ct`/trace sharing
  config/default_config.yaml
  src/ct/launch/launch.nim
  src/ct/online_sharing/security_upload.nim
  src/ct/online_sharing/trace_manager.nim
  src/ct/trace/record.nim
  src/ct/trace/storage_and_import.nim
Labels: cla-signed, trace sharing, command line interface, ct entrypoint

#61 fix: Install subwindow checkbox :after element
  src/config/default_config.yaml
  src/frontend/styles/subwindow.styl
Labels: cla-signed

#71 fix(appimage): Integrate zip and ssh dynlib for online functionality
  appimage-scripts/build_appimage.sh
  appimage-scripts/build_with_nim.sh
  nix/packages/default.nix
Labels: cla-signed, build, linux, trace sharing

#74 fix(dmg): Add libzip dylib
  non-nix-build/build.sh
  non-nix-build/build_in_simple_env.sh
  non-nix-build/install_libraries.sh
Labels: cla-signed

#75 Fix(dmg): Call install_libraries.sh
  non-nix-build/build.sh
Labels: cla-signed

#81 release: release 25.03.2
  .github/workflows/codetracer.yml
  CHANGELOG.md
  src/ct/version.nim
Labels: cla-signed, build

#82 docs: update release links in README, add a release checklist, based on Zahary's feedback
  README.md
  release_checklist.md
Labels: documentation, cla-signed

#83 fix(dmg): Prefer linking through nim than relying on mac dynamic loading
  non-nix-build/build.sh
  non-nix-build/build_with_nim.sh
  non-nix-build/install_libraries.sh
Labels: cla-signed
