Repository metacraft-labs/codetracer, pull requests merged in 2025-06, with the labels that each got.

#164 Implement Ruby each loop detection
  .agents/codebase-insights.txt
  src/db-backend/src/expr_loader.rs
Labels: cla-signed, codex

#158 Get commit hashes and repo names from flake.lock
  non-nix-build/find_git_hash_from_lockfile.py
  non-nix-build/install_nargo.sh
  non-nix-build/install_wazero.sh
Labels: bug, cla-signed, build, packaging, macos

#171 Add basic DAP client and session test
  src/db-backend/src/dap.rs
  src/db-backend/src/lib.rs
  src/db-backend/tests/dap_protocol.rs
  src/db-backend/tests/dap_session.rs
Labels: cla-signed, codex

#172 feat(tui): add simple ratatui interface
  src/tui/Cargo.toml
  src/tui/src/simple_main.rs
Labels: cla-signed, codex

#177 feat: send trace data with launch
  src/db-backend/src/dap.rs
  src/db-backend/src/dap_server.rs
  src/db-backend/src/main.rs
  src/db-backend/tests/dap_backend_server.rs
  src/db-backend/tests/dap_protocol.rs
  src/db-backend/tests/dap_session.rs
Labels: cla-signed, codex

#180 Add simple DAP client to TUI
  .agents/codebase-insights.txt
  src/tui/src/dap_client.rs
  src/tui/src/simple_main.rs
Labels: cla-signed, codex

#183 feat: DAP client uses per-process socket path
  .agents/codebase-insights.txt
  src/tui/src/dap_client.rs
Labels: cla-signed, codex

#185 Implement socket path argument for DAP server
  src/db-backend/src/main.rs
  src/db-backend/tests/dap_backend_server.rs
Labels: cla-signed, codex

#199 Implement DAP initialize step in simple-tui
  .agents/tasks/2025/06/05-1717-fix-send-initialize.txt
  src/tui/src/dap_client.rs
  src/tui/src/simple_main.rs
Labels: cla-signed, codex

#200 feat(db-backend): stop execution on launch
  .agents/tasks/2025/06/05-1336-stop-launch-entry.txt
  src/db-backend/src/dap_server.rs
  src/db-backend/tests/dap_backend_server.rs
  src/db-backend/tests/dap_session.rs
Labels: cla-signed, codex

#202 Refactor DAP server to use handler
  src/db-backend/src/dap_server.rs
  src/db-backend/src/main.rs
Labels: cla-signed, codex

#205 Add reverse steps to DAP server
  .agents/tasks/2025/06/06-1326-add-reverse-steps.txt
  src/db-backend/src/dap_server.rs
Labels: cla-signed, codex

#208 Add BigInt comparison handling
  .agents/tasks/2025/06/06-1357-bigint-compare.txt
  src/db-backend/src/tracepoint_interpreter/operator_functions.rs
Labels: cla-signed, codex

#210 Add stdio transport for db-backend DAP
  .agents/codebase-insights.txt
  src/db-backend/src/dap_server.rs
  src/db-backend/src/main.rs
  src/db-backend/tests/dap_backend_stdio.rs
Labels: cla-signed, codex

#212 Add configurationDone to DAP
  .agents/codebase-insights.txt
  .agents/tasks/2025/06/09-1454-feat-add-support-for-configuration-done-dap
  src/db-backend/src/dap_server.rs
  src/db-backend/tests/dap_backend_server.rs
  src/db-backend/tests/dap_backend_stdio.rs
  src/db-backend/tests/dap_session.rs
Labels: cla-signed, codex

#217 fix: fix type errors for ui tests state spec; test with tsc in ui-tests CI
  ci/lint/ui-tests.sh
  ui-tests/.gitignore
  ui-tests/tests/page_objects/state.ts
Labels: bug, cla-signed, test, ci

#207 Add Ruby checklist folder rename
  .agents/tasks/2025/06/06-1627-ruby-checklist.txt
  ui-tests/programs/rb_checklist/blocks_and_iterators.rb
  ui-tests/programs/rb_checklist/concurrency.rb
  ui-tests/programs/rb_checklist/control_structures.rb
  ui-tests/programs/rb_checklist/data_types.rb
  ui-tests/programs/rb_checklist/exceptions.rb
  ui-tests/programs/rb_checklist/io_and_external.rb
  ui-tests/programs/rb_checklist/metaprogramming.rb
  ui-tests/programs/rb_checklist/oop.rb
  ui-tests/programs/rb_checklist/special_features.rb
  ui-tests/programs/rb_checklist/variables_and_constants.rb
Labels: cla-signed, codex

#222 fix: prevent text selection in footer
  .agents/tasks/2025/06/05-1719-footer-no-select.txt
  src/frontend/styles/components/status_bar.styl
Labels: cla-signed

#225 feat(stylus): Add start-up commands for working with Stylus
  src/ct/codetracerconf.nim
  src/ct/launch/electron.nim
  src/ct/launch/launch.nim
Labels: cla-signed

#223 feat(cargo-stylus): Add cargo-stylus as a dependency to the ct package
  appimage-scripts/build_appimage.sh
  flake.lock
  flake.nix
  nix/packages/default.nix
  nix/shells/main.nix
Labels: cla-signed
